# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Set Curve Refinement', kernelModule='curve_refinement_kernel', kernelFunction='curveRefinement', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgGroupBox(name='GroupBox_1', p='DialogBox', text='Choose Refinement Level', layout='LAYOUT_FILL_X')
RsgRadioButton(p='GroupBox_1', text='Extra Coarse', keyword='kw_crl', default=False)
RsgRadioButton(p='GroupBox_1', text='Coarse', keyword='kw_crl', default=False)
RsgRadioButton(p='GroupBox_1', text='Medium', keyword='kw_crl', default=False)
RsgRadioButton(p='GroupBox_1', text='Fine', keyword='kw_crl', default=True)
RsgRadioButton(p='GroupBox_1', text='Extra Fine', keyword='kw_crl', default=False)
dialogBox.show()